[package]
name = "mtgjson-rust"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of MTGJSON data structures with Python bindings"
license = "MIT"

[lib]
name = "mtgjson_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pyo3 = { version = "0.22", features = ["extension-module", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["serde", "v4", "v5"] }
regex = "1.0"
thiserror = "1.0"
indexmap = { version = "2.0", features = ["serde"] }

# Network and async dependencies
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
sha2 = "0.10"

# Additional dependencies for set builder functionality
unicode-normalization = "0.1"
futures = "0.3"
url = "2.0"
base64 = "0.21"
once_cell = "1.0"
lazy_static = "1.4"

[dev-dependencies]
anyhow = "1.0"